# This workflows will run tests on Ubuntu
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Ubuntu

on: push
#   release:
#     types: [created]

jobs:
  tests:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Update git buffer
      run: |
        # Somehow the brew install fails when running action. Let's try and increment buffer size.
        git config --global http.postBuffer 524288000
    - name: Install setuptools
      run: |
        sudo pip3 install setuptools wheel twine
        sudo apt-get -y install curl unzip
    - name: Install ta-lib
      run: |
        mkdir -p talib && cd talib && \
          pip3 install numpy && \
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
          tar -xvzf ta-lib-0.4.0-src.tar.gz && \
          cd ta-lib/ && \
          ./configure --prefix=/usr && \
          sudo make && \
          sudo make install && \
          cd /home/runner/work/nseta/nseta
        sudo rm -rf talib
        pip3 install ta-lib==0.4.19
        python3 -c 'import numpy, talib; close = numpy.random.random(100); output = talib.SMA(close); print(output)'
    - name: Install fastquant
      run: |
        cd /home/runner/work/nseta/nseta
        pip3 install fastquant==0.1.3.25
    - name: Install fbprophet
      run: |
        cd /home/runner/work/nseta/nseta
        mkdir -p fbprophet && cd fbprophet && \
          curl -L -O https://files.pythonhosted.org/packages/1a/b5/9c3fefa8a7b839729df57deedf0a69815841dfb88f0df911f34d998230b7/fbprophet-0.7.1.tar.gz \
            && tar -xzf fbprophet-0.7.1.tar.gz \
            && rm -rf fbprophet-0.7.1.tar.gz
        sudo apt-get -y install libc-dev
        sudo apt-get update && sudo apt-get -y install build-essential
        pip3 install -r fbprophet-0.7.1/requirements.txt
        pip3 install ipython==7.5.0
        pip3 install fbprophet==0.7.1
    - name: Install project dependencies
      run: |
        pwd
        pip3 install --upgrade pip
        pip3 install convertdate>=2.3.0
        pip3 install sanic==19.12.2
        pip3 install multidict==4.6
        python3 setup.py clean build install
        python3 -c "from nseta.scanner.volumeScanner import volumeScanner; from nseta.scanner.baseStockScanner import ScannerType; s=volumeScanner(ScannerType.Volume,['HDFC']); s.scan();"
    - name: Generate test coverage report
      run: |
        pip3 install timeout-decorator
        pip3 install coverage
        coverage run -m unittest discover -s tests -p 'test_*.py'
        coverage report -m
        coverage html
        bash <(curl -s https://codecov.io/bash)
    - name: "Upload test coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        # files: ./coverage1.xml,./coverage2.xml
        # directory: ./coverage/reports/
        flags: unittests
        env_vars: THIS_VERSION,GITHUB_REF
        name: codecov-umbrella
        fail_ci_if_error: false
        # path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
    - name: "Upload test coverage to Codacy"
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        coverage xml
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Python -r coverage.xml
    - name: clean up
      run: |
        sudo rm -rf build
        sudo rm -rf dist
